#include "components/spc/spc_original_sample_interval.h"

#include <array>
#include <cassert>
#include <cmath>

int main() {
    using namespace gameaudio::spc;

    std::array<float, 64> original{};
    for (std::size_t index = 0; index < original.size(); ++index) {
        // Deliberately retain structure between integer game-grid points. With a
        // 2:1 upstream/game mapping, odd upstream indices are information the
        // prepared game grid could discard before BRR.
        original[index] = static_cast<float>(
            0.55 * std::sin(static_cast<double>(index) * 0.37)
            + 0.20 * std::sin(static_cast<double>(index) * 1.11));
    }

    spc_sample_restoration_candidate candidate;
    candidate.game_brr_identity = {1, 2};
    candidate.upstream_identity = {3, 4};
    candidate.relation = spc_sample_lineage_relation::exact_pre_brr_source;
    candidate.evidence = spc_sample_restoration_evidence::exact_upstream_source;
    candidate.upstream = {original.data(), original.size(), 48000.0, 1.0};
    candidate.coordinate_map.game_origin = 0.0;
    candidate.coordinate_map.upstream_origin = 0.0;
    candidate.coordinate_map.upstream_frames_per_game_sample = 2.0;
    candidate.coordinate_map.preparation_chain_exact = true;
    candidate.identity_validation_passed = true;
    assert(may_use_spc_sample_restoration_automatically(candidate));

    spc_original_sample_control_interval interval;
    interval.source = &candidate;
    interval.start_q12 = 8 * 4096;
    interval.pitch_step_q12 = 4096;
    interval.envelope = 0x0400; // exact 1/2 game envelope

    const auto phase0 = reconstruct_spc_original_sample_interval(interval, 0.0);
    const auto phase_half = reconstruct_spc_original_sample_interval(interval, 0.5);
    assert(phase0.valid);
    assert(phase_half.valid);
    assert(std::abs(phase0.game_position - 8.0) < 1.0e-12);
    assert(std::abs(phase_half.game_position - 8.5) < 1.0e-12);
    assert(std::abs(phase0.source_normalized - phase_half.source_normalized) > 1.0e-4);
    assert(std::abs(
        phase_half.post_envelope_normalized
        - phase_half.source_normalized * 0.5) < 1.0e-12);

    // This top rung cannot substitute an unproven corpus match.
    auto unproven = candidate;
    unproven.identity_validation_passed = false;
    interval.source = &unproven;
    assert(!reconstruct_spc_original_sample_interval(interval, 0.5).valid);

    // NON/noise is generated by the S-DSP and is not an upstream sample-library
    // waveform, so original-sample restoration deliberately yields to hardware.
    interval.source = &candidate;
    interval.noise_enabled = true;
    assert(!reconstruct_spc_original_sample_interval(interval, 0.5).valid);

    // Native boundary ownership stays unique.
    interval.noise_enabled = false;
    assert(!reconstruct_spc_original_sample_interval(interval, 1.0).valid);

    return 0;
}
